### ISSUE TITLE
When I click on GitHub on Connect To GitHub dialog nothing happens

### ISSUE THREAD

**Issue by hovek** [github/VisualStudio#1575]
I've just updated the extension and restarted VS multiple times. I can't connect and get other projects from GitHub.  GitHub Enterprise is the only thing available.

![image](https://user-images.githubusercontent.com/5937551/38205951-d26973e6-36a8-11e8-82ab-c8d9aec9b2a5.png)

**Comment by meaghanlewis** [comment]
👋 @hovek. This looks like the same issue that was described here: https://github.com/github/VisualStudio/issues/1094 that _should_ have been fixed a few months ago. Mind trying the steps to fix this listed [there](https://github.com/github/VisualStudio/issues/1094#issuecomment-334406719).

I'm also curious as to what version of Visual Studio and what version of the extension you are using.

**Comment by hovek** [comment]
I have everything up to date, all newest; VS v17.6 and extension v2.4.3.1737

**Comment by grokys** [comment]
Hi @hovek. Ok, it looks like we still have a bug here. Could you try the following:

- Open Credential Manager from the Windows Start Menu
- Delete all "Generic Credentials" that mention "github"
- Delete the `ghfvs.connections` file from `C:\Users\[Username]\AppData\Local\GìtHubVisualStudio`

And see if that fixes it?

**Comment by hovek** [comment]
Yes, that has fixed it.

**Comment by grokys** [comment]
Ok, I'm not quite sure what was going wrong there, it could be that the problem was introduced by an older version before the upgrade to 2.4.3. I'm going to close this out and we'll monitor to see if anyone else has this problem. Thanks!
