### ISSUE TITLE
Unable to clone any project.

### ISSUE THREAD

**Issue by TommasoScalici** [github/VisualStudio#772]
When I try to clone a repository I always get an error with this message:

> "Failed to clone the repository **'censored'**
> Email support@github.com if you continue to have problems."

- GitHub Extension for Visual Studio version: 2.1.1.4
- Visual Studio version: 2017 RC (15.0.26020.0)

Steps: I just login to my GitHub account, try to clone a random project and then I get the error.
Logs:

**extensions.log**

> 2017-01-14 01:23:20.5659|INFO|thread: 1|RepositoryHost|Log in from cache for login **censored** to host 'https://api.github.com/' SUCCEEDED
> 2017-01-14 01:23:20.5680|INFO|thread: 1|RepositoryHosts|Log in to GitHub.com host 'https://api.github.com/' with username **'censored'** SUCCEEDED
> 2017-01-14 01:24:01.4342|ERROR|thread: 1|RepositoryCloneService|Could not clone https://github.com/ **censored**.git to C:\Users\\**censored**\Documents\Visual Studio 2017\Projects\\**censored**. System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
>    in GitHub.Services.VSGitServices.Clone(String cloneUrl, String clonePath, Boolean recurseSubmodules) in C:\Users\grokys\Documents\GitHub\VisualStudio\src\GitHub.TeamFoundation.14\Services\VSGitServices.cs:riga 60
>    in GitHub.Services.RepositoryCloneService.<>c__DisplayClass5_0.<<CloneRepository>b__0>d.MoveNext() in C:\Users\grokys\Documents\GitHub\VisualStudio\src\GitHub.App\Services\RepositoryCloneService.cs:riga 56
> 

**GitHubVisualStudio-te.log**

> Error loading the repository list from the registry 'System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
>    in GitHub.TeamFoundation.RegistryHelper.PokeTheRegistryForRepositoryList() in C:\Users\grokys\Documents\GitHub\VisualStudio\src\GitHub.TeamFoundation.15\RegistryHelper.cs:riga 26

**Comment by grokys** [comment]
Hi @TommasoScalici - is this still a problem with the latest version of the extension (2.2.0.6)?

**Comment by TommasoScalici** [comment]
Hi @grokys, this seems fixed in 2.2.0.6
I close the issue.

**Comment by BrilliantTechie** [comment]
i still have the issue with VS2017 RTM, and extension 2.2.0.6

**Comment by BrilliantTechie** [comment]
i still have the issue with VS2017 RTM, and extension 2.2.0.6

**Comment by BorisovichAndrey** [comment]
Still has issue with VS2017 Enterprise and extension 2.2.0.11

**Comment by grokys** [comment]
This would appear to be the same issue as #948 - moving the discussion to there as some MS folks are involved too. The problem would appear to be a VS one.

**Comment by andrewwerner1** [comment]
I also have this issue. Not sure if its because I'm using a private/secure Repo. Maybe I will continue to just use command line. Its odd because I can even see the repo through the visual studio extension. I just downloaded the extension tonight so I think I have the latest version.

**Comment by dsdude123** [comment]
This issue has reappeared on all of my machines.

**Comment by Gmedico** [comment]
The issue happens here too. I downloaded and installed GitHub extension today.

**Comment by mewest88** [comment]
I am also having this version with Visual Studios Enterprise 2017 version 15.7.1 GitHub extension 2.5.2.2566.

I just installed Visual Studios about 1 week ago and just installed the extension today. It seems to fail while 'Resolving Deltas'.
